version: "3"

services:
  node_server:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.3
    restart: always
    env_file:
      - .env
    expose:
      - 3306
